// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiTokenScopes      apiTokenContextKey      = "apiToken.Scopes"
	SessionCookieScopes sessionCookieContextKey = "sessionCookie.Scopes"
)

// Defines values for BootstrapResponseApiVersion.
const (
	BootstrapResponseApiVersionV1 BootstrapResponseApiVersion = "v1"
)

// Valid indicates whether the value is a known member of the BootstrapResponseApiVersion enum.
func (e BootstrapResponseApiVersion) Valid() bool {
	switch e {
	case BootstrapResponseApiVersionV1:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapResponseMode.
const (
	Lan      BootstrapResponseMode = "lan"
	Personal BootstrapResponseMode = "personal"
)

// Valid indicates whether the value is a known member of the BootstrapResponseMode enum.
func (e BootstrapResponseMode) Valid() bool {
	switch e {
	case Lan:
		return true
	case Personal:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapResponseRuleSchemaVersion.
const (
	BootstrapResponseRuleSchemaVersionN1 BootstrapResponseRuleSchemaVersion = 1
)

// Valid indicates whether the value is a known member of the BootstrapResponseRuleSchemaVersion enum.
func (e BootstrapResponseRuleSchemaVersion) Valid() bool {
	switch e {
	case BootstrapResponseRuleSchemaVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapResponseSortProtocolVersion.
const (
	BootstrapResponseSortProtocolVersionN1 BootstrapResponseSortProtocolVersion = 1
)

// Valid indicates whether the value is a known member of the BootstrapResponseSortProtocolVersion enum.
func (e BootstrapResponseSortProtocolVersion) Valid() bool {
	switch e {
	case BootstrapResponseSortProtocolVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapResponseWebsocketProtocolVersion.
const (
	N1 BootstrapResponseWebsocketProtocolVersion = 1
)

// Valid indicates whether the value is a known member of the BootstrapResponseWebsocketProtocolVersion enum.
func (e BootstrapResponseWebsocketProtocolVersion) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for ContentBlobRefAlgorithm.
const (
	Sha256V1 ContentBlobRefAlgorithm = "sha256-v1"
)

// Valid indicates whether the value is a known member of the ContentBlobRefAlgorithm enum.
func (e ContentBlobRefAlgorithm) Valid() bool {
	switch e {
	case Sha256V1:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	APPDIRSSOURCEOVERLAP      ErrorCode = "APPDIRS_SOURCE_OVERLAP"
	BACKUPFAILED              ErrorCode = "BACKUP_FAILED"
	CATALOGPUBLICATIONMISSING ErrorCode = "CATALOG_PUBLICATION_MISSING"
	CONFIGINVALID             ErrorCode = "CONFIG_INVALID"
	CONFLICT                  ErrorCode = "CONFLICT"
	CONTENTCHANGEDDURINGHASH  ErrorCode = "CONTENT_CHANGED_DURING_HASH"
	CSRFINVALID               ErrorCode = "CSRF_INVALID"
	CURSOREXPIRED             ErrorCode = "CURSOR_EXPIRED"
	CURSORINVALID             ErrorCode = "CURSOR_INVALID"
	DATABASEOPENFAILED        ErrorCode = "DATABASE_OPEN_FAILED"
	FORBIDDEN                 ErrorCode = "FORBIDDEN"
	HOSTREJECTED              ErrorCode = "HOST_REJECTED"
	INTERNALERROR             ErrorCode = "INTERNAL_ERROR"
	MEDIAOFFLINE              ErrorCode = "MEDIA_OFFLINE"
	MIGRATIONFAILED           ErrorCode = "MIGRATION_FAILED"
	NOTFOUND                  ErrorCode = "NOT_FOUND"
	ORIGINREJECTED            ErrorCode = "ORIGIN_REJECTED"
	PAIRINGEXPIRED            ErrorCode = "PAIRING_EXPIRED"
	PAIRINGINVALID            ErrorCode = "PAIRING_INVALID"
	RULEEVALERROR             ErrorCode = "RULE_EVAL_ERROR"
	RULEPARAMETERINVALID      ErrorCode = "RULE_PARAMETER_INVALID"
	RULESCHEMAINVALID         ErrorCode = "RULE_SCHEMA_INVALID"
	SOURCEPATHINVALID         ErrorCode = "SOURCE_PATH_INVALID"
	SOURCEROOTSOVERLAP        ErrorCode = "SOURCE_ROOTS_OVERLAP"
	UNAUTHENTICATED           ErrorCode = "UNAUTHENTICATED"
	VALIDATIONERROR           ErrorCode = "VALIDATION_ERROR"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case APPDIRSSOURCEOVERLAP:
		return true
	case BACKUPFAILED:
		return true
	case CATALOGPUBLICATIONMISSING:
		return true
	case CONFIGINVALID:
		return true
	case CONFLICT:
		return true
	case CONTENTCHANGEDDURINGHASH:
		return true
	case CSRFINVALID:
		return true
	case CURSOREXPIRED:
		return true
	case CURSORINVALID:
		return true
	case DATABASEOPENFAILED:
		return true
	case FORBIDDEN:
		return true
	case HOSTREJECTED:
		return true
	case INTERNALERROR:
		return true
	case MEDIAOFFLINE:
		return true
	case MIGRATIONFAILED:
		return true
	case NOTFOUND:
		return true
	case ORIGINREJECTED:
		return true
	case PAIRINGEXPIRED:
		return true
	case PAIRINGINVALID:
		return true
	case RULEEVALERROR:
		return true
	case RULEPARAMETERINVALID:
		return true
	case RULESCHEMAINVALID:
		return true
	case SOURCEPATHINVALID:
		return true
	case SOURCEROOTSOVERLAP:
		return true
	case UNAUTHENTICATED:
		return true
	case VALIDATIONERROR:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseApiVersion.
const (
	HealthResponseApiVersionV1 HealthResponseApiVersion = "v1"
)

// Valid indicates whether the value is a known member of the HealthResponseApiVersion enum.
func (e HealthResponseApiVersion) Valid() bool {
	switch e {
	case HealthResponseApiVersionV1:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseDatabasesCatalog.
const (
	HealthResponseDatabasesCatalogOk HealthResponseDatabasesCatalog = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseDatabasesCatalog enum.
func (e HealthResponseDatabasesCatalog) Valid() bool {
	switch e {
	case HealthResponseDatabasesCatalogOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseDatabasesControl.
const (
	HealthResponseDatabasesControlOk HealthResponseDatabasesControl = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseDatabasesControl enum.
func (e HealthResponseDatabasesControl) Valid() bool {
	switch e {
	case HealthResponseDatabasesControlOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// BootstrapResponse defines model for BootstrapResponse.
type BootstrapResponse struct {
	ApiVersion               BootstrapResponseApiVersion               `json:"apiVersion"`
	Authenticated            bool                                      `json:"authenticated"`
	AvailableCapabilities    []string                                  `json:"availableCapabilities"`
	CsrfToken                string                                    `json:"csrfToken"`
	EffectiveCapabilities    []string                                  `json:"effectiveCapabilities"`
	Mode                     BootstrapResponseMode                     `json:"mode"`
	PrincipalId              *string                                   `json:"principalId,omitempty"`
	RuleSchemaVersion        BootstrapResponseRuleSchemaVersion        `json:"ruleSchemaVersion"`
	SortProtocolVersion      BootstrapResponseSortProtocolVersion      `json:"sortProtocolVersion"`
	WebsocketProtocolVersion BootstrapResponseWebsocketProtocolVersion `json:"websocketProtocolVersion"`
}

// BootstrapResponseApiVersion defines model for BootstrapResponse.ApiVersion.
type BootstrapResponseApiVersion string

// BootstrapResponseMode defines model for BootstrapResponse.Mode.
type BootstrapResponseMode string

// BootstrapResponseRuleSchemaVersion defines model for BootstrapResponse.RuleSchemaVersion.
type BootstrapResponseRuleSchemaVersion int

// BootstrapResponseSortProtocolVersion defines model for BootstrapResponse.SortProtocolVersion.
type BootstrapResponseSortProtocolVersion int

// BootstrapResponseWebsocketProtocolVersion defines model for BootstrapResponse.WebsocketProtocolVersion.
type BootstrapResponseWebsocketProtocolVersion int

// CanonicalCreatorId defines model for CanonicalCreatorId.
type CanonicalCreatorId = string

// CanonicalMediaId defines model for CanonicalMediaId.
type CanonicalMediaId = string

// CanonicalWorkId defines model for CanonicalWorkId.
type CanonicalWorkId = string

// ContentBlobRef defines model for ContentBlobRef.
type ContentBlobRef struct {
	Algorithm ContentBlobRefAlgorithm `json:"algorithm"`
	Digest    string                  `json:"digest"`
}

// ContentBlobRefAlgorithm defines model for ContentBlobRef.Algorithm.
type ContentBlobRefAlgorithm string

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code          ErrorCode `json:"code"`
	CorrelationId string    `json:"correlationId"`
	Field         *string   `json:"field,omitempty"`
	Retryable     bool      `json:"retryable"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error ErrorDetail `json:"error"`
}

// FileLocationRef defines model for FileLocationRef.
type FileLocationRef struct {
	IdentityVersion int      `json:"identityVersion"`
	LocationKey     string   `json:"locationKey"`
	SourceId        SourceId `json:"sourceId"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	ApiVersion HealthResponseApiVersion `json:"apiVersion"`
	Databases  struct {
		Catalog HealthResponseDatabasesCatalog `json:"catalog"`
		Control HealthResponseDatabasesControl `json:"control"`
	} `json:"databases"`
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseApiVersion defines model for HealthResponse.ApiVersion.
type HealthResponseApiVersion string

// HealthResponseDatabasesCatalog defines model for HealthResponse.Databases.Catalog.
type HealthResponseDatabasesCatalog string

// HealthResponseDatabasesControl defines model for HealthResponse.Databases.Control.
type HealthResponseDatabasesControl string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// JobId defines model for JobId.
type JobId = string

// Library defines model for Library.
type Library struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        LibraryId `json:"id"`
	Name      string    `json:"name"`
}

// LibraryCreateRequest defines model for LibraryCreateRequest.
type LibraryCreateRequest struct {
	Name string `json:"name"`
}

// LibraryId defines model for LibraryId.
type LibraryId = string

// PairingAttemptResponse defines model for PairingAttemptResponse.
type PairingAttemptResponse struct {
	Credential string    `json:"credential"`
	ExpiresAt  time.Time `json:"expiresAt"`
}

// PairingExchangeRequest defines model for PairingExchangeRequest.
type PairingExchangeRequest struct {
	Credential string `json:"credential"`
}

// QueryPublicationId defines model for QueryPublicationId.
type QueryPublicationId = string

// RuleVersion defines model for RuleVersion.
type RuleVersion struct {
	CreatedAt    time.Time    `json:"createdAt"`
	PackageHash  SHA256Digest `json:"packageHash"`
	RuleIrHash   SHA256Digest `json:"ruleIrHash"`
	RuleSetId    string       `json:"ruleSetId"`
	SemanticHash SHA256Digest `json:"semanticHash"`
	Version      string       `json:"version"`
}

// RuleVersionCreateRequest defines model for RuleVersionCreateRequest.
type RuleVersionCreateRequest struct {
	Package map[string]interface{} `json:"package"`
}

// SHA256Digest defines model for SHA256Digest.
type SHA256Digest = string

// SessionEstablishedResponse defines model for SessionEstablishedResponse.
type SessionEstablishedResponse struct {
	CsrfToken             string         `json:"csrfToken"`
	EffectiveCapabilities []string       `json:"effectiveCapabilities"`
	Session               SessionSummary `json:"session"`
}

// SessionId defines model for SessionId.
type SessionId = string

// SessionSummary defines model for SessionSummary.
type SessionSummary struct {
	CreatedAt   time.Time `json:"createdAt"`
	ExpiresAt   time.Time `json:"expiresAt"`
	Id          SessionId `json:"id"`
	LastSeenAt  time.Time `json:"lastSeenAt"`
	PrincipalId string    `json:"principalId"`
	Revoked     bool      `json:"revoked"`
}

// Source defines model for Source.
type Source struct {
	Available   bool      `json:"available"`
	CreatedAt   time.Time `json:"createdAt"`
	DisplayName string    `json:"displayName"`
	Id          SourceId  `json:"id"`
	LibraryId   LibraryId `json:"libraryId"`
	ReadOnly    bool      `json:"readOnly"`
}

// SourceCreateRequest defines model for SourceCreateRequest.
type SourceCreateRequest struct {
	DisplayName string    `json:"displayName"`
	LibraryId   LibraryId `json:"libraryId"`
	RootPath    string    `json:"rootPath"`
}

// SourceId defines model for SourceId.
type SourceId = string

// SourceRuleBinding defines model for SourceRuleBinding.
type SourceRuleBinding struct {
	CreatedAt    time.Time              `json:"createdAt"`
	Id           SourceRuleBindingId    `json:"id"`
	Parameters   map[string]interface{} `json:"parameters"`
	Priority     int                    `json:"priority"`
	RuleIrHash   SHA256Digest           `json:"ruleIrHash"`
	SemanticHash SHA256Digest           `json:"semanticHash"`
	SourceId     SourceId               `json:"sourceId"`
}

// SourceRuleBindingCreateRequest defines model for SourceRuleBindingCreateRequest.
type SourceRuleBindingCreateRequest struct {
	Parameters   map[string]interface{} `json:"parameters"`
	Priority     int                    `json:"priority"`
	SemanticHash SHA256Digest           `json:"semanticHash"`
	SourceId     SourceId               `json:"sourceId"`
}

// SourceRuleBindingId defines model for SourceRuleBindingId.
type SourceRuleBindingId = string

// CSRFHeader defines model for CSRFHeader.
type CSRFHeader = string

// ConflictError defines model for ConflictError.
type ConflictError = ErrorEnvelope

// ForbiddenError defines model for ForbiddenError.
type ForbiddenError = ErrorEnvelope

// InternalError defines model for InternalError.
type InternalError = ErrorEnvelope

// NotFoundError defines model for NotFoundError.
type NotFoundError = ErrorEnvelope

// UnauthenticatedError defines model for UnauthenticatedError.
type UnauthenticatedError = ErrorEnvelope

// ValidationError defines model for ValidationError.
type ValidationError = ErrorEnvelope

// apiTokenContextKey is the context key for apiToken security scheme
type apiTokenContextKey string

// sessionCookieContextKey is the context key for sessionCookie security scheme
type sessionCookieContextKey string

// CreateLibraryParams defines parameters for CreateLibrary.
type CreateLibraryParams struct {
	XGalleryCSRF CSRFHeader `json:"X-Gallery-CSRF"`
}

// ExchangePairingCredentialParams defines parameters for ExchangePairingCredential.
type ExchangePairingCredentialParams struct {
	XGalleryCSRF CSRFHeader `json:"X-Gallery-CSRF"`
}

// CreatePairingAttemptParams defines parameters for CreatePairingAttempt.
type CreatePairingAttemptParams struct {
	XGalleryCSRF CSRFHeader `json:"X-Gallery-CSRF"`
}

// CreateRuleVersionParams defines parameters for CreateRuleVersion.
type CreateRuleVersionParams struct {
	XGalleryCSRF CSRFHeader `json:"X-Gallery-CSRF"`
}

// RevokeSessionParams defines parameters for RevokeSession.
type RevokeSessionParams struct {
	XGalleryCSRF CSRFHeader `json:"X-Gallery-CSRF"`
}

// CreateSourceRuleBindingParams defines parameters for CreateSourceRuleBinding.
type CreateSourceRuleBindingParams struct {
	XGalleryCSRF CSRFHeader `json:"X-Gallery-CSRF"`
}

// CreateSourceParams defines parameters for CreateSource.
type CreateSourceParams struct {
	XGalleryCSRF CSRFHeader `json:"X-Gallery-CSRF"`
}

// CreateLibraryJSONRequestBody defines body for CreateLibrary for application/json ContentType.
type CreateLibraryJSONRequestBody = LibraryCreateRequest

// ExchangePairingCredentialJSONRequestBody defines body for ExchangePairingCredential for application/json ContentType.
type ExchangePairingCredentialJSONRequestBody = PairingExchangeRequest

// CreateRuleVersionJSONRequestBody defines body for CreateRuleVersion for application/json ContentType.
type CreateRuleVersionJSONRequestBody = RuleVersionCreateRequest

// CreateSourceRuleBindingJSONRequestBody defines body for CreateSourceRuleBinding for application/json ContentType.
type CreateSourceRuleBindingJSONRequestBody = SourceRuleBindingCreateRequest

// CreateSourceJSONRequestBody defines body for CreateSource for application/json ContentType.
type CreateSourceJSONRequestBody = SourceCreateRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetBootstrap request
	GetBootstrap(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateLibraryWithBody request with any body
	CreateLibraryWithBody(ctx context.Context, params *CreateLibraryParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateLibrary(ctx context.Context, params *CreateLibraryParams, body CreateLibraryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetLibrary request
	GetLibrary(ctx context.Context, libraryId LibraryId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ExchangePairingCredentialWithBody request with any body
	ExchangePairingCredentialWithBody(ctx context.Context, params *ExchangePairingCredentialParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ExchangePairingCredential(ctx context.Context, params *ExchangePairingCredentialParams, body ExchangePairingCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePairingAttempt request
	CreatePairingAttempt(ctx context.Context, params *CreatePairingAttemptParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateRuleVersionWithBody request with any body
	CreateRuleVersionWithBody(ctx context.Context, params *CreateRuleVersionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateRuleVersion(ctx context.Context, params *CreateRuleVersionParams, body CreateRuleVersionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRuleVersion request
	GetRuleVersion(ctx context.Context, semanticHash SHA256Digest, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListSessions request
	ListSessions(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RevokeSession request
	RevokeSession(ctx context.Context, sessionId SessionId, params *RevokeSessionParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateSourceRuleBindingWithBody request with any body
	CreateSourceRuleBindingWithBody(ctx context.Context, params *CreateSourceRuleBindingParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateSourceRuleBinding(ctx context.Context, params *CreateSourceRuleBindingParams, body CreateSourceRuleBindingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSourceRuleBinding request
	GetSourceRuleBinding(ctx context.Context, bindingId SourceRuleBindingId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateSourceWithBody request with any body
	CreateSourceWithBody(ctx context.Context, params *CreateSourceParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateSource(ctx context.Context, params *CreateSourceParams, body CreateSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSource request
	GetSource(ctx context.Context, sourceId SourceId, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetBootstrap(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBootstrapRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateLibraryWithBody(ctx context.Context, params *CreateLibraryParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateLibraryRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateLibrary(ctx context.Context, params *CreateLibraryParams, body CreateLibraryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateLibraryRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetLibrary(ctx context.Context, libraryId LibraryId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLibraryRequest(c.Server, libraryId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExchangePairingCredentialWithBody(ctx context.Context, params *ExchangePairingCredentialParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExchangePairingCredentialRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExchangePairingCredential(ctx context.Context, params *ExchangePairingCredentialParams, body ExchangePairingCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExchangePairingCredentialRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePairingAttempt(ctx context.Context, params *CreatePairingAttemptParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePairingAttemptRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRuleVersionWithBody(ctx context.Context, params *CreateRuleVersionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRuleVersionRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRuleVersion(ctx context.Context, params *CreateRuleVersionParams, body CreateRuleVersionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRuleVersionRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRuleVersion(ctx context.Context, semanticHash SHA256Digest, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRuleVersionRequest(c.Server, semanticHash)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListSessions(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSessionsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RevokeSession(ctx context.Context, sessionId SessionId, params *RevokeSessionParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeSessionRequest(c.Server, sessionId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateSourceRuleBindingWithBody(ctx context.Context, params *CreateSourceRuleBindingParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateSourceRuleBindingRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateSourceRuleBinding(ctx context.Context, params *CreateSourceRuleBindingParams, body CreateSourceRuleBindingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateSourceRuleBindingRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSourceRuleBinding(ctx context.Context, bindingId SourceRuleBindingId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSourceRuleBindingRequest(c.Server, bindingId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateSourceWithBody(ctx context.Context, params *CreateSourceParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateSourceRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateSource(ctx context.Context, params *CreateSourceParams, body CreateSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateSourceRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSource(ctx context.Context, sourceId SourceId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSourceRequest(c.Server, sourceId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetBootstrapRequest generates requests for GetBootstrap
func NewGetBootstrapRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/bootstrap")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateLibraryRequest calls the generic CreateLibrary builder with application/json body
func NewCreateLibraryRequest(server string, params *CreateLibraryParams, body CreateLibraryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateLibraryRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateLibraryRequestWithBody generates requests for CreateLibrary with any type of body
func NewCreateLibraryRequestWithBody(server string, params *CreateLibraryParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/libraries")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Gallery-CSRF", params.XGalleryCSRF, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Gallery-CSRF", headerParam0)

	}

	return req, nil
}

// NewGetLibraryRequest generates requests for GetLibrary
func NewGetLibraryRequest(server string, libraryId LibraryId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "libraryId", libraryId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/libraries/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewExchangePairingCredentialRequest calls the generic ExchangePairingCredential builder with application/json body
func NewExchangePairingCredentialRequest(server string, params *ExchangePairingCredentialParams, body ExchangePairingCredentialJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewExchangePairingCredentialRequestWithBody(server, params, "application/json", bodyReader)
}

// NewExchangePairingCredentialRequestWithBody generates requests for ExchangePairingCredential with any type of body
func NewExchangePairingCredentialRequestWithBody(server string, params *ExchangePairingCredentialParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/personal/pair")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Gallery-CSRF", params.XGalleryCSRF, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Gallery-CSRF", headerParam0)

	}

	return req, nil
}

// NewCreatePairingAttemptRequest generates requests for CreatePairingAttempt
func NewCreatePairingAttemptRequest(server string, params *CreatePairingAttemptParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/personal/pairing-attempts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Gallery-CSRF", params.XGalleryCSRF, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Gallery-CSRF", headerParam0)

	}

	return req, nil
}

// NewCreateRuleVersionRequest calls the generic CreateRuleVersion builder with application/json body
func NewCreateRuleVersionRequest(server string, params *CreateRuleVersionParams, body CreateRuleVersionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateRuleVersionRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateRuleVersionRequestWithBody generates requests for CreateRuleVersion with any type of body
func NewCreateRuleVersionRequestWithBody(server string, params *CreateRuleVersionParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/rule-versions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Gallery-CSRF", params.XGalleryCSRF, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Gallery-CSRF", headerParam0)

	}

	return req, nil
}

// NewGetRuleVersionRequest generates requests for GetRuleVersion
func NewGetRuleVersionRequest(server string, semanticHash SHA256Digest) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "semanticHash", semanticHash, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/rule-versions/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListSessionsRequest generates requests for ListSessions
func NewListSessionsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/sessions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRevokeSessionRequest generates requests for RevokeSession
func NewRevokeSessionRequest(server string, sessionId SessionId, params *RevokeSessionParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "sessionId", sessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/sessions/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Gallery-CSRF", params.XGalleryCSRF, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Gallery-CSRF", headerParam0)

	}

	return req, nil
}

// NewCreateSourceRuleBindingRequest calls the generic CreateSourceRuleBinding builder with application/json body
func NewCreateSourceRuleBindingRequest(server string, params *CreateSourceRuleBindingParams, body CreateSourceRuleBindingJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateSourceRuleBindingRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateSourceRuleBindingRequestWithBody generates requests for CreateSourceRuleBinding with any type of body
func NewCreateSourceRuleBindingRequestWithBody(server string, params *CreateSourceRuleBindingParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/source-rule-bindings")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Gallery-CSRF", params.XGalleryCSRF, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Gallery-CSRF", headerParam0)

	}

	return req, nil
}

// NewGetSourceRuleBindingRequest generates requests for GetSourceRuleBinding
func NewGetSourceRuleBindingRequest(server string, bindingId SourceRuleBindingId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bindingId", bindingId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/source-rule-bindings/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateSourceRequest calls the generic CreateSource builder with application/json body
func NewCreateSourceRequest(server string, params *CreateSourceParams, body CreateSourceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateSourceRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateSourceRequestWithBody generates requests for CreateSource with any type of body
func NewCreateSourceRequestWithBody(server string, params *CreateSourceParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/sources")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Gallery-CSRF", params.XGalleryCSRF, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Gallery-CSRF", headerParam0)

	}

	return req, nil
}

// NewGetSourceRequest generates requests for GetSource
func NewGetSourceRequest(server string, sourceId SourceId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "sourceId", sourceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/sources/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetBootstrapWithResponse request
	GetBootstrapWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetBootstrapResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// CreateLibraryWithBodyWithResponse request with any body
	CreateLibraryWithBodyWithResponse(ctx context.Context, params *CreateLibraryParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateLibraryResponse, error)

	CreateLibraryWithResponse(ctx context.Context, params *CreateLibraryParams, body CreateLibraryJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateLibraryResponse, error)

	// GetLibraryWithResponse request
	GetLibraryWithResponse(ctx context.Context, libraryId LibraryId, reqEditors ...RequestEditorFn) (*GetLibraryResponse, error)

	// ExchangePairingCredentialWithBodyWithResponse request with any body
	ExchangePairingCredentialWithBodyWithResponse(ctx context.Context, params *ExchangePairingCredentialParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExchangePairingCredentialResponse, error)

	ExchangePairingCredentialWithResponse(ctx context.Context, params *ExchangePairingCredentialParams, body ExchangePairingCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*ExchangePairingCredentialResponse, error)

	// CreatePairingAttemptWithResponse request
	CreatePairingAttemptWithResponse(ctx context.Context, params *CreatePairingAttemptParams, reqEditors ...RequestEditorFn) (*CreatePairingAttemptResponse, error)

	// CreateRuleVersionWithBodyWithResponse request with any body
	CreateRuleVersionWithBodyWithResponse(ctx context.Context, params *CreateRuleVersionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRuleVersionResponse, error)

	CreateRuleVersionWithResponse(ctx context.Context, params *CreateRuleVersionParams, body CreateRuleVersionJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRuleVersionResponse, error)

	// GetRuleVersionWithResponse request
	GetRuleVersionWithResponse(ctx context.Context, semanticHash SHA256Digest, reqEditors ...RequestEditorFn) (*GetRuleVersionResponse, error)

	// ListSessionsWithResponse request
	ListSessionsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSessionsResponse, error)

	// RevokeSessionWithResponse request
	RevokeSessionWithResponse(ctx context.Context, sessionId SessionId, params *RevokeSessionParams, reqEditors ...RequestEditorFn) (*RevokeSessionResponse, error)

	// CreateSourceRuleBindingWithBodyWithResponse request with any body
	CreateSourceRuleBindingWithBodyWithResponse(ctx context.Context, params *CreateSourceRuleBindingParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateSourceRuleBindingResponse, error)

	CreateSourceRuleBindingWithResponse(ctx context.Context, params *CreateSourceRuleBindingParams, body CreateSourceRuleBindingJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateSourceRuleBindingResponse, error)

	// GetSourceRuleBindingWithResponse request
	GetSourceRuleBindingWithResponse(ctx context.Context, bindingId SourceRuleBindingId, reqEditors ...RequestEditorFn) (*GetSourceRuleBindingResponse, error)

	// CreateSourceWithBodyWithResponse request with any body
	CreateSourceWithBodyWithResponse(ctx context.Context, params *CreateSourceParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateSourceResponse, error)

	CreateSourceWithResponse(ctx context.Context, params *CreateSourceParams, body CreateSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateSourceResponse, error)

	// GetSourceWithResponse request
	GetSourceWithResponse(ctx context.Context, sourceId SourceId, reqEditors ...RequestEditorFn) (*GetSourceResponse, error)
}

type GetBootstrapResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BootstrapResponse
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetBootstrapResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBootstrapResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetBootstrapResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateLibraryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Library
	JSON400      *ValidationError
	JSON401      *UnauthenticatedError
	JSON403      *ForbiddenError
}

// Status returns HTTPResponse.Status
func (r CreateLibraryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateLibraryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateLibraryResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetLibraryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Library
	JSON401      *UnauthenticatedError
	JSON403      *ForbiddenError
	JSON404      *NotFoundError
}

// Status returns HTTPResponse.Status
func (r GetLibraryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetLibraryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetLibraryResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ExchangePairingCredentialResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *SessionEstablishedResponse
	JSON401      *UnauthenticatedError
	JSON403      *ForbiddenError
}

// Status returns HTTPResponse.Status
func (r ExchangePairingCredentialResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExchangePairingCredentialResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ExchangePairingCredentialResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreatePairingAttemptResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *PairingAttemptResponse
	JSON403      *ForbiddenError
}

// Status returns HTTPResponse.Status
func (r CreatePairingAttemptResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePairingAttemptResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreatePairingAttemptResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateRuleVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *RuleVersion
	JSON400      *ValidationError
	JSON401      *UnauthenticatedError
	JSON403      *ForbiddenError
	JSON409      *ConflictError
}

// Status returns HTTPResponse.Status
func (r CreateRuleVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateRuleVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateRuleVersionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetRuleVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RuleVersion
	JSON401      *UnauthenticatedError
	JSON403      *ForbiddenError
	JSON404      *NotFoundError
}

// Status returns HTTPResponse.Status
func (r GetRuleVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRuleVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetRuleVersionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListSessionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Sessions []SessionSummary `json:"sessions"`
	}
	JSON401 *UnauthenticatedError
	JSON403 *ForbiddenError
}

// Status returns HTTPResponse.Status
func (r ListSessionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSessionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListSessionsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RevokeSessionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *UnauthenticatedError
	JSON403      *ForbiddenError
	JSON404      *NotFoundError
}

// Status returns HTTPResponse.Status
func (r RevokeSessionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RevokeSessionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RevokeSessionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateSourceRuleBindingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *SourceRuleBinding
	JSON400      *ValidationError
	JSON401      *UnauthenticatedError
	JSON403      *ForbiddenError
	JSON404      *NotFoundError
	JSON409      *ConflictError
}

// Status returns HTTPResponse.Status
func (r CreateSourceRuleBindingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateSourceRuleBindingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateSourceRuleBindingResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetSourceRuleBindingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SourceRuleBinding
	JSON401      *UnauthenticatedError
	JSON403      *ForbiddenError
	JSON404      *NotFoundError
}

// Status returns HTTPResponse.Status
func (r GetSourceRuleBindingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSourceRuleBindingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSourceRuleBindingResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateSourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Source
	JSON400      *ValidationError
	JSON401      *UnauthenticatedError
	JSON403      *ForbiddenError
	JSON409      *ConflictError
}

// Status returns HTTPResponse.Status
func (r CreateSourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateSourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateSourceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetSourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Source
	JSON401      *UnauthenticatedError
	JSON403      *ForbiddenError
	JSON404      *NotFoundError
}

// Status returns HTTPResponse.Status
func (r GetSourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSourceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetBootstrapWithResponse request returning *GetBootstrapResponse
func (c *ClientWithResponses) GetBootstrapWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetBootstrapResponse, error) {
	rsp, err := c.GetBootstrap(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBootstrapResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// CreateLibraryWithBodyWithResponse request with arbitrary body returning *CreateLibraryResponse
func (c *ClientWithResponses) CreateLibraryWithBodyWithResponse(ctx context.Context, params *CreateLibraryParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateLibraryResponse, error) {
	rsp, err := c.CreateLibraryWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateLibraryResponse(rsp)
}

func (c *ClientWithResponses) CreateLibraryWithResponse(ctx context.Context, params *CreateLibraryParams, body CreateLibraryJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateLibraryResponse, error) {
	rsp, err := c.CreateLibrary(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateLibraryResponse(rsp)
}

// GetLibraryWithResponse request returning *GetLibraryResponse
func (c *ClientWithResponses) GetLibraryWithResponse(ctx context.Context, libraryId LibraryId, reqEditors ...RequestEditorFn) (*GetLibraryResponse, error) {
	rsp, err := c.GetLibrary(ctx, libraryId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetLibraryResponse(rsp)
}

// ExchangePairingCredentialWithBodyWithResponse request with arbitrary body returning *ExchangePairingCredentialResponse
func (c *ClientWithResponses) ExchangePairingCredentialWithBodyWithResponse(ctx context.Context, params *ExchangePairingCredentialParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExchangePairingCredentialResponse, error) {
	rsp, err := c.ExchangePairingCredentialWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExchangePairingCredentialResponse(rsp)
}

func (c *ClientWithResponses) ExchangePairingCredentialWithResponse(ctx context.Context, params *ExchangePairingCredentialParams, body ExchangePairingCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*ExchangePairingCredentialResponse, error) {
	rsp, err := c.ExchangePairingCredential(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExchangePairingCredentialResponse(rsp)
}

// CreatePairingAttemptWithResponse request returning *CreatePairingAttemptResponse
func (c *ClientWithResponses) CreatePairingAttemptWithResponse(ctx context.Context, params *CreatePairingAttemptParams, reqEditors ...RequestEditorFn) (*CreatePairingAttemptResponse, error) {
	rsp, err := c.CreatePairingAttempt(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePairingAttemptResponse(rsp)
}

// CreateRuleVersionWithBodyWithResponse request with arbitrary body returning *CreateRuleVersionResponse
func (c *ClientWithResponses) CreateRuleVersionWithBodyWithResponse(ctx context.Context, params *CreateRuleVersionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRuleVersionResponse, error) {
	rsp, err := c.CreateRuleVersionWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRuleVersionResponse(rsp)
}

func (c *ClientWithResponses) CreateRuleVersionWithResponse(ctx context.Context, params *CreateRuleVersionParams, body CreateRuleVersionJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRuleVersionResponse, error) {
	rsp, err := c.CreateRuleVersion(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRuleVersionResponse(rsp)
}

// GetRuleVersionWithResponse request returning *GetRuleVersionResponse
func (c *ClientWithResponses) GetRuleVersionWithResponse(ctx context.Context, semanticHash SHA256Digest, reqEditors ...RequestEditorFn) (*GetRuleVersionResponse, error) {
	rsp, err := c.GetRuleVersion(ctx, semanticHash, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRuleVersionResponse(rsp)
}

// ListSessionsWithResponse request returning *ListSessionsResponse
func (c *ClientWithResponses) ListSessionsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSessionsResponse, error) {
	rsp, err := c.ListSessions(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSessionsResponse(rsp)
}

// RevokeSessionWithResponse request returning *RevokeSessionResponse
func (c *ClientWithResponses) RevokeSessionWithResponse(ctx context.Context, sessionId SessionId, params *RevokeSessionParams, reqEditors ...RequestEditorFn) (*RevokeSessionResponse, error) {
	rsp, err := c.RevokeSession(ctx, sessionId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeSessionResponse(rsp)
}

// CreateSourceRuleBindingWithBodyWithResponse request with arbitrary body returning *CreateSourceRuleBindingResponse
func (c *ClientWithResponses) CreateSourceRuleBindingWithBodyWithResponse(ctx context.Context, params *CreateSourceRuleBindingParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateSourceRuleBindingResponse, error) {
	rsp, err := c.CreateSourceRuleBindingWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateSourceRuleBindingResponse(rsp)
}

func (c *ClientWithResponses) CreateSourceRuleBindingWithResponse(ctx context.Context, params *CreateSourceRuleBindingParams, body CreateSourceRuleBindingJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateSourceRuleBindingResponse, error) {
	rsp, err := c.CreateSourceRuleBinding(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateSourceRuleBindingResponse(rsp)
}

// GetSourceRuleBindingWithResponse request returning *GetSourceRuleBindingResponse
func (c *ClientWithResponses) GetSourceRuleBindingWithResponse(ctx context.Context, bindingId SourceRuleBindingId, reqEditors ...RequestEditorFn) (*GetSourceRuleBindingResponse, error) {
	rsp, err := c.GetSourceRuleBinding(ctx, bindingId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSourceRuleBindingResponse(rsp)
}

// CreateSourceWithBodyWithResponse request with arbitrary body returning *CreateSourceResponse
func (c *ClientWithResponses) CreateSourceWithBodyWithResponse(ctx context.Context, params *CreateSourceParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateSourceResponse, error) {
	rsp, err := c.CreateSourceWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateSourceResponse(rsp)
}

func (c *ClientWithResponses) CreateSourceWithResponse(ctx context.Context, params *CreateSourceParams, body CreateSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateSourceResponse, error) {
	rsp, err := c.CreateSource(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateSourceResponse(rsp)
}

// GetSourceWithResponse request returning *GetSourceResponse
func (c *ClientWithResponses) GetSourceWithResponse(ctx context.Context, sourceId SourceId, reqEditors ...RequestEditorFn) (*GetSourceResponse, error) {
	rsp, err := c.GetSource(ctx, sourceId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSourceResponse(rsp)
}

// ParseGetBootstrapResponse parses an HTTP response from a GetBootstrapWithResponse call
func ParseGetBootstrapResponse(rsp *http.Response) (*GetBootstrapResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBootstrapResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BootstrapResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateLibraryResponse parses an HTTP response from a CreateLibraryWithResponse call
func ParseCreateLibraryResponse(rsp *http.Response) (*CreateLibraryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateLibraryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Library
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthenticatedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseGetLibraryResponse parses an HTTP response from a GetLibraryWithResponse call
func ParseGetLibraryResponse(rsp *http.Response) (*GetLibraryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetLibraryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Library
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthenticatedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseExchangePairingCredentialResponse parses an HTTP response from a ExchangePairingCredentialWithResponse call
func ParseExchangePairingCredentialResponse(rsp *http.Response) (*ExchangePairingCredentialResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExchangePairingCredentialResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest SessionEstablishedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthenticatedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseCreatePairingAttemptResponse parses an HTTP response from a CreatePairingAttemptWithResponse call
func ParseCreatePairingAttemptResponse(rsp *http.Response) (*CreatePairingAttemptResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePairingAttemptResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest PairingAttemptResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseCreateRuleVersionResponse parses an HTTP response from a CreateRuleVersionWithResponse call
func ParseCreateRuleVersionResponse(rsp *http.Response) (*CreateRuleVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateRuleVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest RuleVersion
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthenticatedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ConflictError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseGetRuleVersionResponse parses an HTTP response from a GetRuleVersionWithResponse call
func ParseGetRuleVersionResponse(rsp *http.Response) (*GetRuleVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRuleVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RuleVersion
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthenticatedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseListSessionsResponse parses an HTTP response from a ListSessionsWithResponse call
func ParseListSessionsResponse(rsp *http.Response) (*ListSessionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSessionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Sessions []SessionSummary `json:"sessions"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthenticatedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseRevokeSessionResponse parses an HTTP response from a RevokeSessionWithResponse call
func ParseRevokeSessionResponse(rsp *http.Response) (*RevokeSessionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RevokeSessionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthenticatedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseCreateSourceRuleBindingResponse parses an HTTP response from a CreateSourceRuleBindingWithResponse call
func ParseCreateSourceRuleBindingResponse(rsp *http.Response) (*CreateSourceRuleBindingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateSourceRuleBindingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest SourceRuleBinding
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthenticatedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ConflictError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseGetSourceRuleBindingResponse parses an HTTP response from a GetSourceRuleBindingWithResponse call
func ParseGetSourceRuleBindingResponse(rsp *http.Response) (*GetSourceRuleBindingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSourceRuleBindingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SourceRuleBinding
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthenticatedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseCreateSourceResponse parses an HTTP response from a CreateSourceWithResponse call
func ParseCreateSourceResponse(rsp *http.Response) (*CreateSourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateSourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Source
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthenticatedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ConflictError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseGetSourceResponse parses an HTTP response from a GetSourceWithResponse call
func ParseGetSourceResponse(rsp *http.Response) (*GetSourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Source
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthenticatedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
