// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiTokenScopes      apiTokenContextKey      = "apiToken.Scopes"
	SessionCookieScopes sessionCookieContextKey = "sessionCookie.Scopes"
)

// Defines values for BootstrapResponseApiVersion.
const (
	BootstrapResponseApiVersionV1 BootstrapResponseApiVersion = "v1"
)

// Valid indicates whether the value is a known member of the BootstrapResponseApiVersion enum.
func (e BootstrapResponseApiVersion) Valid() bool {
	switch e {
	case BootstrapResponseApiVersionV1:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapResponseMode.
const (
	Lan      BootstrapResponseMode = "lan"
	Personal BootstrapResponseMode = "personal"
)

// Valid indicates whether the value is a known member of the BootstrapResponseMode enum.
func (e BootstrapResponseMode) Valid() bool {
	switch e {
	case Lan:
		return true
	case Personal:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapResponseRuleSchemaVersion.
const (
	BootstrapResponseRuleSchemaVersionN1 BootstrapResponseRuleSchemaVersion = 1
)

// Valid indicates whether the value is a known member of the BootstrapResponseRuleSchemaVersion enum.
func (e BootstrapResponseRuleSchemaVersion) Valid() bool {
	switch e {
	case BootstrapResponseRuleSchemaVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapResponseSortProtocolVersion.
const (
	BootstrapResponseSortProtocolVersionN1 BootstrapResponseSortProtocolVersion = 1
)

// Valid indicates whether the value is a known member of the BootstrapResponseSortProtocolVersion enum.
func (e BootstrapResponseSortProtocolVersion) Valid() bool {
	switch e {
	case BootstrapResponseSortProtocolVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapResponseWebsocketProtocolVersion.
const (
	N1 BootstrapResponseWebsocketProtocolVersion = 1
)

// Valid indicates whether the value is a known member of the BootstrapResponseWebsocketProtocolVersion enum.
func (e BootstrapResponseWebsocketProtocolVersion) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for ContentBlobRefAlgorithm.
const (
	Sha256V1 ContentBlobRefAlgorithm = "sha256-v1"
)

// Valid indicates whether the value is a known member of the ContentBlobRefAlgorithm enum.
func (e ContentBlobRefAlgorithm) Valid() bool {
	switch e {
	case Sha256V1:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	APPDIRSSOURCEOVERLAP      ErrorCode = "APPDIRS_SOURCE_OVERLAP"
	BACKUPFAILED              ErrorCode = "BACKUP_FAILED"
	CATALOGPUBLICATIONMISSING ErrorCode = "CATALOG_PUBLICATION_MISSING"
	CONFIGINVALID             ErrorCode = "CONFIG_INVALID"
	CONFLICT                  ErrorCode = "CONFLICT"
	CONTENTCHANGEDDURINGHASH  ErrorCode = "CONTENT_CHANGED_DURING_HASH"
	CSRFINVALID               ErrorCode = "CSRF_INVALID"
	CURSOREXPIRED             ErrorCode = "CURSOR_EXPIRED"
	CURSORINVALID             ErrorCode = "CURSOR_INVALID"
	DATABASEOPENFAILED        ErrorCode = "DATABASE_OPEN_FAILED"
	FORBIDDEN                 ErrorCode = "FORBIDDEN"
	HOSTREJECTED              ErrorCode = "HOST_REJECTED"
	INTERNALERROR             ErrorCode = "INTERNAL_ERROR"
	MEDIAOFFLINE              ErrorCode = "MEDIA_OFFLINE"
	MIGRATIONFAILED           ErrorCode = "MIGRATION_FAILED"
	NOTFOUND                  ErrorCode = "NOT_FOUND"
	ORIGINREJECTED            ErrorCode = "ORIGIN_REJECTED"
	PAIRINGEXPIRED            ErrorCode = "PAIRING_EXPIRED"
	PAIRINGINVALID            ErrorCode = "PAIRING_INVALID"
	RULEEVALERROR             ErrorCode = "RULE_EVAL_ERROR"
	RULESCHEMAINVALID         ErrorCode = "RULE_SCHEMA_INVALID"
	SOURCEROOTSOVERLAP        ErrorCode = "SOURCE_ROOTS_OVERLAP"
	UNAUTHENTICATED           ErrorCode = "UNAUTHENTICATED"
	VALIDATIONERROR           ErrorCode = "VALIDATION_ERROR"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case APPDIRSSOURCEOVERLAP:
		return true
	case BACKUPFAILED:
		return true
	case CATALOGPUBLICATIONMISSING:
		return true
	case CONFIGINVALID:
		return true
	case CONFLICT:
		return true
	case CONTENTCHANGEDDURINGHASH:
		return true
	case CSRFINVALID:
		return true
	case CURSOREXPIRED:
		return true
	case CURSORINVALID:
		return true
	case DATABASEOPENFAILED:
		return true
	case FORBIDDEN:
		return true
	case HOSTREJECTED:
		return true
	case INTERNALERROR:
		return true
	case MEDIAOFFLINE:
		return true
	case MIGRATIONFAILED:
		return true
	case NOTFOUND:
		return true
	case ORIGINREJECTED:
		return true
	case PAIRINGEXPIRED:
		return true
	case PAIRINGINVALID:
		return true
	case RULEEVALERROR:
		return true
	case RULESCHEMAINVALID:
		return true
	case SOURCEROOTSOVERLAP:
		return true
	case UNAUTHENTICATED:
		return true
	case VALIDATIONERROR:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseApiVersion.
const (
	HealthResponseApiVersionV1 HealthResponseApiVersion = "v1"
)

// Valid indicates whether the value is a known member of the HealthResponseApiVersion enum.
func (e HealthResponseApiVersion) Valid() bool {
	switch e {
	case HealthResponseApiVersionV1:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseDatabasesCatalog.
const (
	HealthResponseDatabasesCatalogOk HealthResponseDatabasesCatalog = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseDatabasesCatalog enum.
func (e HealthResponseDatabasesCatalog) Valid() bool {
	switch e {
	case HealthResponseDatabasesCatalogOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseDatabasesControl.
const (
	HealthResponseDatabasesControlOk HealthResponseDatabasesControl = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseDatabasesControl enum.
func (e HealthResponseDatabasesControl) Valid() bool {
	switch e {
	case HealthResponseDatabasesControlOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// BootstrapResponse defines model for BootstrapResponse.
type BootstrapResponse struct {
	ApiVersion               BootstrapResponseApiVersion               `json:"apiVersion"`
	Authenticated            bool                                      `json:"authenticated"`
	AvailableCapabilities    []string                                  `json:"availableCapabilities"`
	CsrfToken                string                                    `json:"csrfToken"`
	EffectiveCapabilities    []string                                  `json:"effectiveCapabilities"`
	Mode                     BootstrapResponseMode                     `json:"mode"`
	PrincipalId              *string                                   `json:"principalId,omitempty"`
	RuleSchemaVersion        BootstrapResponseRuleSchemaVersion        `json:"ruleSchemaVersion"`
	SortProtocolVersion      BootstrapResponseSortProtocolVersion      `json:"sortProtocolVersion"`
	WebsocketProtocolVersion BootstrapResponseWebsocketProtocolVersion `json:"websocketProtocolVersion"`
}

// BootstrapResponseApiVersion defines model for BootstrapResponse.ApiVersion.
type BootstrapResponseApiVersion string

// BootstrapResponseMode defines model for BootstrapResponse.Mode.
type BootstrapResponseMode string

// BootstrapResponseRuleSchemaVersion defines model for BootstrapResponse.RuleSchemaVersion.
type BootstrapResponseRuleSchemaVersion int

// BootstrapResponseSortProtocolVersion defines model for BootstrapResponse.SortProtocolVersion.
type BootstrapResponseSortProtocolVersion int

// BootstrapResponseWebsocketProtocolVersion defines model for BootstrapResponse.WebsocketProtocolVersion.
type BootstrapResponseWebsocketProtocolVersion int

// CanonicalCreatorId defines model for CanonicalCreatorId.
type CanonicalCreatorId = string

// CanonicalMediaId defines model for CanonicalMediaId.
type CanonicalMediaId = string

// CanonicalWorkId defines model for CanonicalWorkId.
type CanonicalWorkId = string

// ContentBlobRef defines model for ContentBlobRef.
type ContentBlobRef struct {
	Algorithm ContentBlobRefAlgorithm `json:"algorithm"`
	Digest    string                  `json:"digest"`
}

// ContentBlobRefAlgorithm defines model for ContentBlobRef.Algorithm.
type ContentBlobRefAlgorithm string

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code          ErrorCode `json:"code"`
	CorrelationId string    `json:"correlationId"`
	Field         *string   `json:"field,omitempty"`
	Retryable     bool      `json:"retryable"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error ErrorDetail `json:"error"`
}

// FileLocationRef defines model for FileLocationRef.
type FileLocationRef struct {
	IdentityVersion int      `json:"identityVersion"`
	LocationKey     string   `json:"locationKey"`
	SourceId        SourceId `json:"sourceId"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	ApiVersion HealthResponseApiVersion `json:"apiVersion"`
	Databases  struct {
		Catalog HealthResponseDatabasesCatalog `json:"catalog"`
		Control HealthResponseDatabasesControl `json:"control"`
	} `json:"databases"`
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseApiVersion defines model for HealthResponse.ApiVersion.
type HealthResponseApiVersion string

// HealthResponseDatabasesCatalog defines model for HealthResponse.Databases.Catalog.
type HealthResponseDatabasesCatalog string

// HealthResponseDatabasesControl defines model for HealthResponse.Databases.Control.
type HealthResponseDatabasesControl string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// JobId defines model for JobId.
type JobId = string

// LibraryId defines model for LibraryId.
type LibraryId = string

// PairingAttemptResponse defines model for PairingAttemptResponse.
type PairingAttemptResponse struct {
	Credential string    `json:"credential"`
	ExpiresAt  time.Time `json:"expiresAt"`
}

// PairingExchangeRequest defines model for PairingExchangeRequest.
type PairingExchangeRequest struct {
	Credential string `json:"credential"`
}

// QueryPublicationId defines model for QueryPublicationId.
type QueryPublicationId = string

// SessionEstablishedResponse defines model for SessionEstablishedResponse.
type SessionEstablishedResponse struct {
	CsrfToken             string         `json:"csrfToken"`
	EffectiveCapabilities []string       `json:"effectiveCapabilities"`
	Session               SessionSummary `json:"session"`
}

// SessionId defines model for SessionId.
type SessionId = string

// SessionSummary defines model for SessionSummary.
type SessionSummary struct {
	CreatedAt   time.Time `json:"createdAt"`
	ExpiresAt   time.Time `json:"expiresAt"`
	Id          SessionId `json:"id"`
	LastSeenAt  time.Time `json:"lastSeenAt"`
	PrincipalId string    `json:"principalId"`
	Revoked     bool      `json:"revoked"`
}

// SourceId defines model for SourceId.
type SourceId = string

// SourceRuleBindingId defines model for SourceRuleBindingId.
type SourceRuleBindingId = string

// CSRFHeader defines model for CSRFHeader.
type CSRFHeader = string

// ForbiddenError defines model for ForbiddenError.
type ForbiddenError = ErrorEnvelope

// InternalError defines model for InternalError.
type InternalError = ErrorEnvelope

// NotFoundError defines model for NotFoundError.
type NotFoundError = ErrorEnvelope

// UnauthenticatedError defines model for UnauthenticatedError.
type UnauthenticatedError = ErrorEnvelope

// apiTokenContextKey is the context key for apiToken security scheme
type apiTokenContextKey string

// sessionCookieContextKey is the context key for sessionCookie security scheme
type sessionCookieContextKey string

// ExchangePairingCredentialParams defines parameters for ExchangePairingCredential.
type ExchangePairingCredentialParams struct {
	XGalleryCSRF CSRFHeader `json:"X-Gallery-CSRF"`
}

// CreatePairingAttemptParams defines parameters for CreatePairingAttempt.
type CreatePairingAttemptParams struct {
	XGalleryCSRF CSRFHeader `json:"X-Gallery-CSRF"`
}

// RevokeSessionParams defines parameters for RevokeSession.
type RevokeSessionParams struct {
	XGalleryCSRF CSRFHeader `json:"X-Gallery-CSRF"`
}

// ExchangePairingCredentialJSONRequestBody defines body for ExchangePairingCredential for application/json ContentType.
type ExchangePairingCredentialJSONRequestBody = PairingExchangeRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetBootstrap request
	GetBootstrap(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ExchangePairingCredentialWithBody request with any body
	ExchangePairingCredentialWithBody(ctx context.Context, params *ExchangePairingCredentialParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ExchangePairingCredential(ctx context.Context, params *ExchangePairingCredentialParams, body ExchangePairingCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePairingAttempt request
	CreatePairingAttempt(ctx context.Context, params *CreatePairingAttemptParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListSessions request
	ListSessions(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RevokeSession request
	RevokeSession(ctx context.Context, sessionId SessionId, params *RevokeSessionParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetBootstrap(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBootstrapRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExchangePairingCredentialWithBody(ctx context.Context, params *ExchangePairingCredentialParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExchangePairingCredentialRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExchangePairingCredential(ctx context.Context, params *ExchangePairingCredentialParams, body ExchangePairingCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExchangePairingCredentialRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePairingAttempt(ctx context.Context, params *CreatePairingAttemptParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePairingAttemptRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListSessions(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSessionsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RevokeSession(ctx context.Context, sessionId SessionId, params *RevokeSessionParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeSessionRequest(c.Server, sessionId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetBootstrapRequest generates requests for GetBootstrap
func NewGetBootstrapRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/bootstrap")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewExchangePairingCredentialRequest calls the generic ExchangePairingCredential builder with application/json body
func NewExchangePairingCredentialRequest(server string, params *ExchangePairingCredentialParams, body ExchangePairingCredentialJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewExchangePairingCredentialRequestWithBody(server, params, "application/json", bodyReader)
}

// NewExchangePairingCredentialRequestWithBody generates requests for ExchangePairingCredential with any type of body
func NewExchangePairingCredentialRequestWithBody(server string, params *ExchangePairingCredentialParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/personal/pair")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Gallery-CSRF", params.XGalleryCSRF, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Gallery-CSRF", headerParam0)

	}

	return req, nil
}

// NewCreatePairingAttemptRequest generates requests for CreatePairingAttempt
func NewCreatePairingAttemptRequest(server string, params *CreatePairingAttemptParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/personal/pairing-attempts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Gallery-CSRF", params.XGalleryCSRF, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Gallery-CSRF", headerParam0)

	}

	return req, nil
}

// NewListSessionsRequest generates requests for ListSessions
func NewListSessionsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/sessions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRevokeSessionRequest generates requests for RevokeSession
func NewRevokeSessionRequest(server string, sessionId SessionId, params *RevokeSessionParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "sessionId", sessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/sessions/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Gallery-CSRF", params.XGalleryCSRF, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Gallery-CSRF", headerParam0)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetBootstrapWithResponse request
	GetBootstrapWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetBootstrapResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// ExchangePairingCredentialWithBodyWithResponse request with any body
	ExchangePairingCredentialWithBodyWithResponse(ctx context.Context, params *ExchangePairingCredentialParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExchangePairingCredentialResponse, error)

	ExchangePairingCredentialWithResponse(ctx context.Context, params *ExchangePairingCredentialParams, body ExchangePairingCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*ExchangePairingCredentialResponse, error)

	// CreatePairingAttemptWithResponse request
	CreatePairingAttemptWithResponse(ctx context.Context, params *CreatePairingAttemptParams, reqEditors ...RequestEditorFn) (*CreatePairingAttemptResponse, error)

	// ListSessionsWithResponse request
	ListSessionsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSessionsResponse, error)

	// RevokeSessionWithResponse request
	RevokeSessionWithResponse(ctx context.Context, sessionId SessionId, params *RevokeSessionParams, reqEditors ...RequestEditorFn) (*RevokeSessionResponse, error)
}

type GetBootstrapResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BootstrapResponse
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetBootstrapResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBootstrapResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetBootstrapResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ExchangePairingCredentialResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *SessionEstablishedResponse
	JSON401      *UnauthenticatedError
	JSON403      *ForbiddenError
}

// Status returns HTTPResponse.Status
func (r ExchangePairingCredentialResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExchangePairingCredentialResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ExchangePairingCredentialResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreatePairingAttemptResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *PairingAttemptResponse
	JSON403      *ForbiddenError
}

// Status returns HTTPResponse.Status
func (r CreatePairingAttemptResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePairingAttemptResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreatePairingAttemptResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListSessionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Sessions []SessionSummary `json:"sessions"`
	}
	JSON401 *UnauthenticatedError
	JSON403 *ForbiddenError
}

// Status returns HTTPResponse.Status
func (r ListSessionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSessionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListSessionsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RevokeSessionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *UnauthenticatedError
	JSON403      *ForbiddenError
	JSON404      *NotFoundError
}

// Status returns HTTPResponse.Status
func (r RevokeSessionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RevokeSessionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RevokeSessionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetBootstrapWithResponse request returning *GetBootstrapResponse
func (c *ClientWithResponses) GetBootstrapWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetBootstrapResponse, error) {
	rsp, err := c.GetBootstrap(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBootstrapResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ExchangePairingCredentialWithBodyWithResponse request with arbitrary body returning *ExchangePairingCredentialResponse
func (c *ClientWithResponses) ExchangePairingCredentialWithBodyWithResponse(ctx context.Context, params *ExchangePairingCredentialParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExchangePairingCredentialResponse, error) {
	rsp, err := c.ExchangePairingCredentialWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExchangePairingCredentialResponse(rsp)
}

func (c *ClientWithResponses) ExchangePairingCredentialWithResponse(ctx context.Context, params *ExchangePairingCredentialParams, body ExchangePairingCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*ExchangePairingCredentialResponse, error) {
	rsp, err := c.ExchangePairingCredential(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExchangePairingCredentialResponse(rsp)
}

// CreatePairingAttemptWithResponse request returning *CreatePairingAttemptResponse
func (c *ClientWithResponses) CreatePairingAttemptWithResponse(ctx context.Context, params *CreatePairingAttemptParams, reqEditors ...RequestEditorFn) (*CreatePairingAttemptResponse, error) {
	rsp, err := c.CreatePairingAttempt(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePairingAttemptResponse(rsp)
}

// ListSessionsWithResponse request returning *ListSessionsResponse
func (c *ClientWithResponses) ListSessionsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSessionsResponse, error) {
	rsp, err := c.ListSessions(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSessionsResponse(rsp)
}

// RevokeSessionWithResponse request returning *RevokeSessionResponse
func (c *ClientWithResponses) RevokeSessionWithResponse(ctx context.Context, sessionId SessionId, params *RevokeSessionParams, reqEditors ...RequestEditorFn) (*RevokeSessionResponse, error) {
	rsp, err := c.RevokeSession(ctx, sessionId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeSessionResponse(rsp)
}

// ParseGetBootstrapResponse parses an HTTP response from a GetBootstrapWithResponse call
func ParseGetBootstrapResponse(rsp *http.Response) (*GetBootstrapResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBootstrapResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BootstrapResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseExchangePairingCredentialResponse parses an HTTP response from a ExchangePairingCredentialWithResponse call
func ParseExchangePairingCredentialResponse(rsp *http.Response) (*ExchangePairingCredentialResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExchangePairingCredentialResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest SessionEstablishedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthenticatedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseCreatePairingAttemptResponse parses an HTTP response from a CreatePairingAttemptWithResponse call
func ParseCreatePairingAttemptResponse(rsp *http.Response) (*CreatePairingAttemptResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePairingAttemptResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest PairingAttemptResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseListSessionsResponse parses an HTTP response from a ListSessionsWithResponse call
func ParseListSessionsResponse(rsp *http.Response) (*ListSessionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSessionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Sessions []SessionSummary `json:"sessions"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthenticatedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseRevokeSessionResponse parses an HTTP response from a RevokeSessionWithResponse call
func ParseRevokeSessionResponse(rsp *http.Response) (*RevokeSessionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RevokeSessionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthenticatedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
