// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// Defines values for BootstrapResponseApiVersion.
const (
	BootstrapResponseApiVersionV1 BootstrapResponseApiVersion = "v1"
)

// Valid indicates whether the value is a known member of the BootstrapResponseApiVersion enum.
func (e BootstrapResponseApiVersion) Valid() bool {
	switch e {
	case BootstrapResponseApiVersionV1:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapResponseMode.
const (
	Lan      BootstrapResponseMode = "lan"
	Personal BootstrapResponseMode = "personal"
)

// Valid indicates whether the value is a known member of the BootstrapResponseMode enum.
func (e BootstrapResponseMode) Valid() bool {
	switch e {
	case Lan:
		return true
	case Personal:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapResponseRuleSchemaVersion.
const (
	BootstrapResponseRuleSchemaVersionN1 BootstrapResponseRuleSchemaVersion = 1
)

// Valid indicates whether the value is a known member of the BootstrapResponseRuleSchemaVersion enum.
func (e BootstrapResponseRuleSchemaVersion) Valid() bool {
	switch e {
	case BootstrapResponseRuleSchemaVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapResponseSortProtocolVersion.
const (
	BootstrapResponseSortProtocolVersionN1 BootstrapResponseSortProtocolVersion = 1
)

// Valid indicates whether the value is a known member of the BootstrapResponseSortProtocolVersion enum.
func (e BootstrapResponseSortProtocolVersion) Valid() bool {
	switch e {
	case BootstrapResponseSortProtocolVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapResponseWebsocketProtocolVersion.
const (
	N1 BootstrapResponseWebsocketProtocolVersion = 1
)

// Valid indicates whether the value is a known member of the BootstrapResponseWebsocketProtocolVersion enum.
func (e BootstrapResponseWebsocketProtocolVersion) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for ContentBlobRefAlgorithm.
const (
	Sha256V1 ContentBlobRefAlgorithm = "sha256-v1"
)

// Valid indicates whether the value is a known member of the ContentBlobRefAlgorithm enum.
func (e ContentBlobRefAlgorithm) Valid() bool {
	switch e {
	case Sha256V1:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	APPDIRSSOURCEOVERLAP      ErrorCode = "APPDIRS_SOURCE_OVERLAP"
	BACKUPFAILED              ErrorCode = "BACKUP_FAILED"
	CATALOGPUBLICATIONMISSING ErrorCode = "CATALOG_PUBLICATION_MISSING"
	CONFIGINVALID             ErrorCode = "CONFIG_INVALID"
	CONFLICT                  ErrorCode = "CONFLICT"
	CONTENTCHANGEDDURINGHASH  ErrorCode = "CONTENT_CHANGED_DURING_HASH"
	CURSOREXPIRED             ErrorCode = "CURSOR_EXPIRED"
	CURSORINVALID             ErrorCode = "CURSOR_INVALID"
	DATABASEOPENFAILED        ErrorCode = "DATABASE_OPEN_FAILED"
	FORBIDDEN                 ErrorCode = "FORBIDDEN"
	INTERNALERROR             ErrorCode = "INTERNAL_ERROR"
	MEDIAOFFLINE              ErrorCode = "MEDIA_OFFLINE"
	MIGRATIONFAILED           ErrorCode = "MIGRATION_FAILED"
	NOTFOUND                  ErrorCode = "NOT_FOUND"
	RULEEVALERROR             ErrorCode = "RULE_EVAL_ERROR"
	RULESCHEMAINVALID         ErrorCode = "RULE_SCHEMA_INVALID"
	SOURCEROOTSOVERLAP        ErrorCode = "SOURCE_ROOTS_OVERLAP"
	UNAUTHENTICATED           ErrorCode = "UNAUTHENTICATED"
	VALIDATIONERROR           ErrorCode = "VALIDATION_ERROR"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case APPDIRSSOURCEOVERLAP:
		return true
	case BACKUPFAILED:
		return true
	case CATALOGPUBLICATIONMISSING:
		return true
	case CONFIGINVALID:
		return true
	case CONFLICT:
		return true
	case CONTENTCHANGEDDURINGHASH:
		return true
	case CURSOREXPIRED:
		return true
	case CURSORINVALID:
		return true
	case DATABASEOPENFAILED:
		return true
	case FORBIDDEN:
		return true
	case INTERNALERROR:
		return true
	case MEDIAOFFLINE:
		return true
	case MIGRATIONFAILED:
		return true
	case NOTFOUND:
		return true
	case RULEEVALERROR:
		return true
	case RULESCHEMAINVALID:
		return true
	case SOURCEROOTSOVERLAP:
		return true
	case UNAUTHENTICATED:
		return true
	case VALIDATIONERROR:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseApiVersion.
const (
	HealthResponseApiVersionV1 HealthResponseApiVersion = "v1"
)

// Valid indicates whether the value is a known member of the HealthResponseApiVersion enum.
func (e HealthResponseApiVersion) Valid() bool {
	switch e {
	case HealthResponseApiVersionV1:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseDatabasesCatalog.
const (
	HealthResponseDatabasesCatalogOk HealthResponseDatabasesCatalog = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseDatabasesCatalog enum.
func (e HealthResponseDatabasesCatalog) Valid() bool {
	switch e {
	case HealthResponseDatabasesCatalogOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseDatabasesControl.
const (
	HealthResponseDatabasesControlOk HealthResponseDatabasesControl = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseDatabasesControl enum.
func (e HealthResponseDatabasesControl) Valid() bool {
	switch e {
	case HealthResponseDatabasesControlOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// BootstrapResponse defines model for BootstrapResponse.
type BootstrapResponse struct {
	ApiVersion               BootstrapResponseApiVersion               `json:"apiVersion"`
	Authenticated            bool                                      `json:"authenticated"`
	EffectiveCapabilities    []string                                  `json:"effectiveCapabilities"`
	Mode                     BootstrapResponseMode                     `json:"mode"`
	PrincipalId              *string                                   `json:"principalId,omitempty"`
	RuleSchemaVersion        BootstrapResponseRuleSchemaVersion        `json:"ruleSchemaVersion"`
	SortProtocolVersion      BootstrapResponseSortProtocolVersion      `json:"sortProtocolVersion"`
	WebsocketProtocolVersion BootstrapResponseWebsocketProtocolVersion `json:"websocketProtocolVersion"`
}

// BootstrapResponseApiVersion defines model for BootstrapResponse.ApiVersion.
type BootstrapResponseApiVersion string

// BootstrapResponseMode defines model for BootstrapResponse.Mode.
type BootstrapResponseMode string

// BootstrapResponseRuleSchemaVersion defines model for BootstrapResponse.RuleSchemaVersion.
type BootstrapResponseRuleSchemaVersion int

// BootstrapResponseSortProtocolVersion defines model for BootstrapResponse.SortProtocolVersion.
type BootstrapResponseSortProtocolVersion int

// BootstrapResponseWebsocketProtocolVersion defines model for BootstrapResponse.WebsocketProtocolVersion.
type BootstrapResponseWebsocketProtocolVersion int

// CanonicalCreatorId defines model for CanonicalCreatorId.
type CanonicalCreatorId = string

// CanonicalMediaId defines model for CanonicalMediaId.
type CanonicalMediaId = string

// CanonicalWorkId defines model for CanonicalWorkId.
type CanonicalWorkId = string

// ContentBlobRef defines model for ContentBlobRef.
type ContentBlobRef struct {
	Algorithm ContentBlobRefAlgorithm `json:"algorithm"`
	Digest    string                  `json:"digest"`
}

// ContentBlobRefAlgorithm defines model for ContentBlobRef.Algorithm.
type ContentBlobRefAlgorithm string

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code          ErrorCode `json:"code"`
	CorrelationId string    `json:"correlationId"`
	Field         *string   `json:"field,omitempty"`
	Retryable     bool      `json:"retryable"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error ErrorDetail `json:"error"`
}

// FileLocationRef defines model for FileLocationRef.
type FileLocationRef struct {
	IdentityVersion int      `json:"identityVersion"`
	LocationKey     string   `json:"locationKey"`
	SourceId        SourceId `json:"sourceId"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	ApiVersion HealthResponseApiVersion `json:"apiVersion"`
	Databases  struct {
		Catalog HealthResponseDatabasesCatalog `json:"catalog"`
		Control HealthResponseDatabasesControl `json:"control"`
	} `json:"databases"`
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseApiVersion defines model for HealthResponse.ApiVersion.
type HealthResponseApiVersion string

// HealthResponseDatabasesCatalog defines model for HealthResponse.Databases.Catalog.
type HealthResponseDatabasesCatalog string

// HealthResponseDatabasesControl defines model for HealthResponse.Databases.Control.
type HealthResponseDatabasesControl string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// JobId defines model for JobId.
type JobId = string

// LibraryId defines model for LibraryId.
type LibraryId = string

// QueryPublicationId defines model for QueryPublicationId.
type QueryPublicationId = string

// SourceId defines model for SourceId.
type SourceId = string

// SourceRuleBindingId defines model for SourceRuleBindingId.
type SourceRuleBindingId = string

// InternalError defines model for InternalError.
type InternalError = ErrorEnvelope

// apiTokenContextKey is the context key for apiToken security scheme
type apiTokenContextKey string

// sessionCookieContextKey is the context key for sessionCookie security scheme
type sessionCookieContextKey string

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetBootstrap request
	GetBootstrap(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetBootstrap(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBootstrapRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetBootstrapRequest generates requests for GetBootstrap
func NewGetBootstrapRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/bootstrap")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetBootstrapWithResponse request
	GetBootstrapWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetBootstrapResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)
}

type GetBootstrapResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BootstrapResponse
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetBootstrapResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBootstrapResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetBootstrapResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetBootstrapWithResponse request returning *GetBootstrapResponse
func (c *ClientWithResponses) GetBootstrapWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetBootstrapResponse, error) {
	rsp, err := c.GetBootstrap(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBootstrapResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ParseGetBootstrapResponse parses an HTTP response from a GetBootstrapWithResponse call
func ParseGetBootstrapResponse(rsp *http.Response) (*GetBootstrapResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBootstrapResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BootstrapResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
